### ISSUE TITLE
Remove "Pending Review" box

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#32]
Can we remove the "Pending Review" box?

It seems like that could be creating the blank space in the "Post Status" box. If I select the blank space, it moves the post to "Pending Review"

<img width="485" alt="Screenshot 2023-09-21 at 3 18 09 PM" src="https://github.com/publishpress/publishpress-statuses/assets/3868028/545732c2-efa9-40ad-8f79-19534c5d5f12">

**Comment by agapetry** [comment]
I don't see a clean way to hide the "Pending Review" checkbox. It's a standard WordPress element that does not have any ID or class name.  We could hide the first checkbox and hit the right target on most installations, but that would risk unexpected results when other editor customizations are active.

The blank space in the status dropdown is not caused by the Pending Review checkbox. It's caused by Safari displaying hidden options as a blank row instead of hiding them completely.
