### ISSUE TITLE
Pending status draggable to Disabled even though disabling is prevented

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#85]
It appears that it's impossible to disable Pending Review. Even when disabled in PublishPress Statues, it still appears:
![Screenshot 2023-12-14 at 12 44 26 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/4b08d654-254e-437c-8c4c-8f4a16ef7504)
![Screenshot 2023-12-14 at 12 45 20 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/faa6e245-2dd2-4321-b5c6-82d90baad3a0)

Should we treat "Pending Review" like "Draft", as a special case that can't be disabled?

**Comment by agapetry** [comment]
@stevejburge It cannot be disabled due to hardcoded WordPress behavior. If you refresh the Statuses page after dragging Pending to the Disabled section, you'll see that the disable is not actually applied. That's intentional, as is the lack of "Disable" action link in the Pending row.  I just need to adjust the table js to visibly reject the drag.

**Comment by stevejburge** [comment]
@agapetry Thanks. I agree. Let's treat it just like "Draft"

**Comment by agapetry** [comment]
@stevejburge I can't treat it just like draft because the ability to adjust the workflow order is important.

**Comment by agapetry** [comment]
@stevejburge I have the fix for this ready to go.

**Comment by stevejburge** [comment]
Great, thanks @agapetry
